services:
  db:
    image: mysql:8.1.0
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: mysql.env

  web:
    build: .
    image: comi:1.0-beta
    restart: always
    volumes:
      - media_volume:/code/media
    ports:
      - "8080:8000"
    environment:
      - DATABASE_HOST=db
      - MYSQL_DATABASE=comic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_PORT=3306
    depends_on:
      - db

volumes:
  mysql_volume:
  media_volume: