version: '2'
services:
  db:
    container_name: mysql_container
    image: mysql:8.1
    user: root
    volumes:
      - "./mysql_volume:/var/lib/mysql"
    ports:
      - "3307:3306"
    env_file: mysql.env
  web:
    container_name: django_container
    build: .
    user: root
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DATABASE=comic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    depends_on:
      - db
volumes:
  mysql_volume:
