# Generated by Django 5.0.6 on 2024-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_name', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('variant', models.CharField(max_length=30)),
                ('printing', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('US', 'Us')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('es', 'Es')], max_length=5)),
            ],
        ),
    ]
