# Generated by Django 5.0.6 on 2025-10-19 08:29

import comics.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('comics', '0001_initial'), ('comics', '0002_artist'), ('comics', '0003_comic'), ('comics', '0004_alter_comic_id'), ('comics', '0005_alter_comic_name'), ('comics', '0006_alter_comic_name'), ('comics', '0007_alter_comic_artists'), ('comics', '0008_alter_comic_name'), ('comics', '0009_publishing_year'), ('comics', '0010_remove_comic_name'), ('comics', '0011_printing_alter_comic_artists_alter_comic_price_and_more'), ('comics', '0012_publishing_printing'), ('comics', '0013_remove_comic_artists'), ('comics', '0014_participation'), ('comics', '0015_delete_participation'), ('comics', '0016_comic_artists'), ('comics', '0017_alter_comic_artists'), ('comics', '0018_remove_comic_serie_publishing_serie'), ('comics', '0019_collection_collector_collection_collector_id'), ('comics', '0020_dealer_alter_comic_variant_alter_collection_dealer'), ('comics', '0021_rename_collector_id_collection_collector_and_more'), ('comics', '0022_publishing_date'), ('comics', '0023_comic_ratio_storyarc'), ('comics', '0024_alter_collection_dealer'), ('comics', '0025_comic_details_comic_limited_to'), ('comics', '0026_dealer_real_name_alter_publishing_date_and_more'), ('comics', '0027_dealer_fb'), ('comics', '0028_collection_sale_price_collection_selled_and_more'), ('comics', '0029_alter_publishing_date'), ('comics', '0030_alter_editorial_country_alter_publishing_date_and_more'), ('comics', '0031_alter_collection_collector_alter_collection_comic_and_more'), ('comics', '0032_alter_comic_price'), ('comics', '0033_alter_collection_purchase_price'), ('comics', '0034_alter_publishing_date'), ('comics', '0035_collection_buyer_collection_sale_date'), ('comics', '0036_alter_collection_sale_date'), ('comics', '0037_comic_image_alter_editorial_country_and_more'), ('comics', '0038_alter_comic_image'), ('comics', '0039_rename_purchase_price_collection_amount_and_more'), ('comics', '0040_collection_trade_type'), ('comics', '0041_alter_publishing_date'), ('comics', '0042_collection_valuation'), ('comics', '0043_collection_signatures'), ('comics', '0044_remove_collection_signatures'), ('comics', '0045_alter_comic_ratio_signature_collection_signatures'), ('comics', '0046_alter_publishing_publishing_title_alter_title_name'), ('comics', '0047_rename_collector_collection_collector1'), ('comics', '0048_collection_collector'), ('comics', '0049_alter_collection_collector'), ('comics', '0050_remove_collection_collector1_delete_collector'), ('comics', '0051_remove_collection_buyer_remove_collection_sale_date_and_more'), ('comics', '0052_alter_publishing_year'), ('comics', '0053_publishing_format_alter_publishing_language'), ('comics', '0054_comic_thumbnail_alter_comic_image_and_more'), ('comics', '0055_alter_comic_image'), ('comics', '0056_alter_publishing_format'), ('comics', '0057_comic_format'), ('comics', '0058_remove_publishing_format'), ('comics', '0059_alter_comic_format'), ('comics', '0060_alter_comic_format'), ('comics', '0061_comic_printing'), ('comics', '0062_remove_publishing_printing'), ('comics', '0063_delete_printing_alter_publishing_language'), ('comics', '0064_collection_notes'), ('comics', '0065_signature_price'), ('comics', '0066_comic_compilation_name_comic_is_compilation_and_more'), ('comics', '0067_comic_compiled_issues'), ('comics', '0070_alter_comic_publishing'), ('comics', '0071_alter_comic_publishing'), ('comics', '0072_remove_comic_compilation_name_artist_photo')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(choices=[('MX', 'Mx'), ('US', 'Us'), ('DE', 'De'), ('ES', 'Es')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=5)),
                ('publishing_title', models.CharField(max_length=100)),
                ('editorials', models.ManyToManyField(to='comics.editorial')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.title')),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), comics.models.Publishing.max_value_current_year], verbose_name='year')),
                ('serie', models.CharField(default='1st', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('variant', models.CharField(blank=True, default='A', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('release_date', models.DateField(default=datetime.datetime.now)),
                ('publishing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='comics.publishing')),
                ('artists', models.ManyToManyField(blank=True, to='comics.artist')),
                ('ratio', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_ratio', message='Ratio must be a valid relation Example: (1:100)', regex='^[0-9]{1,3}+:[0-9]{1,3}$')])),
                ('details', models.TextField(blank=True, max_length=500)),
                ('limited_to', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_limit', message='Not a valid number', regex='^[0-9]{0,10}+$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/originals/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('format', models.CharField(choices=[('single_issue', 'Grapa'), ('prestige', 'Prestige'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('ashcan', 'Ashcan'), ('digital', 'Digital')], default='single_issue', max_length=20)),
                ('printing', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], default='1st', max_length=10)),
                ('is_compilation', models.BooleanField(default=False)),
                ('compiled_issues', models.ManyToManyField(blank=True, help_text='Individual issues that are compiled in this comic, if any.', related_name='included_in', to='comics.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(blank=True, max_length=100)),
                ('fb', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StoryArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField()),
                ('publishings', models.ManyToManyField(to='comics.publishing')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('trade_date', models.DateField(default=datetime.datetime.now)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.dealer')),
                ('comic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.comic')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('selled', models.BooleanField(default=False)),
                ('buyer', models.CharField(blank=True, max_length=100)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('trade_type', models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], default='buying', max_length=50)),
                ('valuation', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('has_coa', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.artist')),
                ('collectable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.collection')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='signatures',
            field=models.ManyToManyField(blank=True, through='comics.Signature', to='comics.artist'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='selled',
        ),
        migrations.AddField(
            model_name='collection',
            name='previous_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_trades', to='comics.collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
