# Generated by Django 5.0.6 on 2024-05-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='printing',
        ),
        migrations.RemoveField(
            model_name='title',
            name='language',
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Es')], max_length=5)),
                ('publishing_title', models.CharField(max_length=50)),
                ('printing', models.CharField(max_length=10)),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.editorial')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.title')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='publishing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.publishing'),
        ),
    ]
