# Generated by Django 5.0.6 on 2024-05-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('variant', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('artists', models.ManyToManyField(to='comics.artist')),
                ('publishing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.publishing')),
            ],
        ),
    ]
