# Generated by Django 5.0.6 on 2024-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_alter_comic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
