# Generated by Django 5.0.6 on 2024-05-24 16:14

import comics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_alter_comic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='year',
            field=models.IntegerField(default=1995, validators=[django.core.validators.MinValueValidator(1984), comics.models.Publishing.max_value_current_year], verbose_name='year'),
            preserve_default=False,
        ),
    ]
