# Generated by Django 5.0.6 on 2024-05-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_publishing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='name',
        ),
    ]
