# Generated by Django 5.0.6 on 2024-05-24 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_remove_comic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='artists',
            field=models.ManyToManyField(to='comics.artist'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='comic',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comic',
            name='serie',
            field=models.CharField(default='1st', max_length=20),
        ),
        migrations.AlterField(
            model_name='comic',
            name='variant',
            field=models.CharField(default='A', max_length=30),
        ),
    ]
