# Generated by Django 5.0.6 on 2024-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_printing_alter_comic_artists_alter_comic_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='printing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.printing'),
        ),
    ]
