# Generated by Django 5.0.6 on 2024-05-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0012_publishing_printing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='artists',
        ),
    ]
