# Generated by Django 5.0.6 on 2024-05-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_remove_comic_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.artist')),
                ('comic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.comic')),
            ],
        ),
    ]
