# Generated by Django 5.0.6 on 2024-05-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0014_participation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
