# Generated by Django 5.0.6 on 2024-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0015_delete_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='artists',
            field=models.ManyToManyField(to='comics.artist'),
        ),
    ]
