# Generated by Django 5.0.6 on 2024-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0016_comic_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='artists',
            field=models.ManyToManyField(blank=True, to='comics.artist'),
        ),
    ]
