# Generated by Django 5.0.6 on 2024-05-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0017_alter_comic_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='serie',
        ),
        migrations.AddField(
            model_name='publishing',
            name='serie',
            field=models.CharField(default='1st', max_length=20),
        ),
    ]
