# Generated by Django 5.0.6 on 2024-05-25 08:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0018_remove_comic_serie_publishing_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('acquisition_date', models.DateField(default=datetime.datetime.now)),
                ('dealer', models.CharField(blank=True, max_length=100)),
                ('comic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('comics', models.ManyToManyField(through='comics.Collection', to='comics.comic')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='collector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.collector'),
        ),
    ]
