# Generated by Django 5.0.6 on 2024-05-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0019_collection_collector_collection_collector_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comic',
            name='variant',
            field=models.CharField(blank=True, default='A', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.dealer'),
        ),
    ]
