# Generated by Django 5.0.6 on 2024-06-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0020_dealer_alter_comic_variant_alter_collection_dealer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collector_id',
            new_name='collector',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='comic_id',
            new_name='comic',
        ),
    ]
