# Generated by Django 5.0.6 on 2024-06-02 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0022_publishing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='ratio',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_ratio', message='Ratio must be a valid relation Example: (1:100)', regex='^[0-9]{1,3}+[\\:][0-9]{1,3}$')]),
        ),
        migrations.CreateModel(
            name='StoryArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField()),
                ('publishings', models.ManyToManyField(to='comics.publishing')),
            ],
        ),
    ]
