# Generated by Django 5.0.6 on 2024-06-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0023_comic_ratio_storyarc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics.dealer'),
        ),
    ]
