# Generated by Django 5.0.6 on 2024-06-02 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0024_alter_collection_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comic',
            name='limited_to',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_limit', message='Not a valid number', regex='^[0-9]{0,10}+$')]),
        ),
    ]
