# Generated by Django 5.0.6 on 2024-06-07 23:49

import comics.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0025_comic_details_comic_limited_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='real_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 7)),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), comics.models.Publishing.max_value_current_year], verbose_name='year'),
        ),
    ]
