# Generated by Django 5.0.6 on 2024-06-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0026_dealer_real_name_alter_publishing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='fb',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
