# Generated by Django 5.0.6 on 2024-06-09 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0027_dealer_fb'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='collection',
            name='selled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 9)),
        ),
    ]
