# Generated by Django 5.0.6 on 2024-06-16 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0028_collection_sale_price_collection_selled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
    ]
