# Generated by Django 5.0.6 on 2024-06-23 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0029_alter_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='country',
            field=models.CharField(choices=[('MX', 'Mx'), ('US', 'Us'), ('DE', 'De')], max_length=3),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 23)),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='language',
            field=models.CharField(choices=[('en', 'En'), ('es', 'Es'), ('de', 'De')], max_length=5),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='publishing_title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
