# Generated by Django 5.0.6 on 2024-06-24 03:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0030_alter_editorial_country_alter_publishing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.collector'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.comic'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.dealer'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='publishing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.publishing'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 24)),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='printing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.printing'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.title'),
        ),
    ]
