# Generated by Django 5.0.6 on 2024-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0032_alter_comic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
