# Generated by Django 5.0.6 on 2024-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0034_alter_publishing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='buyer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
