# Generated by Django 5.0.6 on 2024-07-29 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0036_alter_collection_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='country',
            field=models.CharField(choices=[('MX', 'Mx'), ('US', 'Us'), ('DE', 'De'), ('ES', 'Es')], max_length=3),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 29)),
        ),
    ]
