# Generated by Django 5.0.6 on 2024-09-19 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0038_alter_comic_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='purchase_price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='dealer',
            new_name='participant',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='acquisition_date',
            new_name='trade_date',
        ),
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 19)),
        ),
    ]
