# Generated by Django 5.0.6 on 2024-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0039_rename_purchase_price_collection_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='trade_type',
            field=models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling')], default='buying', max_length=50),
        ),
    ]
