# Generated by Django 5.0.6 on 2024-09-19 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0040_collection_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
