# Generated by Django 5.0.6 on 2024-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0041_alter_publishing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
