# Generated by Django 5.0.6 on 2024-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0042_collection_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='signatures',
            field=models.ManyToManyField(blank=True, to='comics.artist'),
        ),
    ]
