# Generated by Django 5.0.6 on 2024-09-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0043_collection_signatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='signatures',
        ),
    ]
