# Generated by Django 5.0.6 on 2024-09-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0046_alter_publishing_publishing_title_alter_title_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collector',
            new_name='collector1',
        ),
    ]
