# Generated by Django 5.0.6 on 2025-08-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0050_remove_collection_collector1_delete_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='selled',
        ),
        migrations.AddField(
            model_name='collection',
            name='previous_trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_trades', to='comics.collection'),
        ),
    ]
