# Generated by Django 5.0.6 on 2025-08-11 07:46

import comics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0051_remove_collection_buyer_remove_collection_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), comics.models.Publishing.max_value_current_year], verbose_name='year'),
        ),
    ]
