# Generated by Django 5.0.6 on 2025-08-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0052_alter_publishing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='format',
            field=models.CharField(choices=[('single_issue', 'Single Issue - Grapa'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('digital', 'Digital')], default='single_issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German')], max_length=5),
        ),
    ]
