# Generated by Django 5.0.6 on 2025-08-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0053_publishing_format_alter_publishing_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/original/'),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='format',
            field=models.CharField(choices=[('single_issue', 'Grapa'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('digital', 'Digital')], default='single_issue', max_length=20),
        ),
    ]
