# Generated by Django 5.0.6 on 2025-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0054_comic_thumbnail_alter_comic_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/originals/'),
        ),
    ]
