# Generated by Django 5.0.6 on 2025-08-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0055_alter_comic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='format',
            field=models.CharField(choices=[('single_issue', 'Grapa'), ('prestige', 'Prestige'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('digital', 'Digital')], default='single_issue', max_length=20),
        ),
    ]
