# Generated by Django 5.0.6 on 2025-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0056_alter_publishing_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='format',
            field=models.CharField(choices=[('single_issue', 'Grapa'), ('prestige', 'Prestige'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('digital', 'Digital')], default='single_issue', max_length=20),
        ),
    ]
