# Generated by Django 5.0.6 on 2025-08-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0057_comic_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing',
            name='format',
        ),
    ]
