# Generated by Django 5.0.6 on 2025-09-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0060_alter_comic_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='printing',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], default='1st', max_length=10),
        ),
    ]
