# Generated by Django 5.0.6 on 2025-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0062_remove_publishing_printing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printing',
        ),
        migrations.AlterField(
            model_name='publishing',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=5),
        ),
    ]
