# Generated by Django 5.0.6 on 2025-09-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0063_delete_printing_alter_publishing_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
