# Generated by Django 5.0.6 on 2025-09-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0064_collection_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
