# Generated by Django 5.0.6 on 2025-09-29 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0065_signature_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='compilation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='is_compilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comic',
            name='publishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comics.publishing'),
        ),
    ]
