# Generated by Django 5.0.6 on 2025-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0066_comic_compilation_name_comic_is_compilation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='compiled_issues',
            field=models.ManyToManyField(blank=True, help_text='Individual issues that are compiled in this comic, if any.', related_name='included_in', to='comics.comic'),
        ),
    ]
