# Generated by Django 5.0.6 on 2025-09-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0070_alter_comic_publishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='publishing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='comics.publishing'),
        ),
    ]
