# Generated by Django 5.0.6 on 2025-10-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0071_alter_comic_publishing"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="artists/photos/"),
        ),
    ]
