# Generated by Django 5.0.6 on 2025-10-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_squashed_0072_remove_comic_compilation_name_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyarc',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
