# Generated by Django 5.0.6 on 2025-11-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0073_storyarc_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='price',
            new_name='cover_price',
        ),
        migrations.AlterField(
            model_name='editorial',
            name='country',
            field=models.CharField(choices=[('MX', 'Mx'), ('US', 'Us'), ('DE', 'De'), ('ES', 'Es'), ('JP', 'Jp')], max_length=3),
        ),
    ]
