# Generated by Django 5.1.10 on 2025-12-25 23:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0074_rename_price_comic_cover_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='GeekCollectable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('trade_date', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collectables/')),
                ('participant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comics.dealer')),
            ],
        ),
    ]
