# Generated by Django 5.1.10 on 2025-12-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0075_alter_dealer_options_geekcollectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='format',
            field=models.CharField(choices=[('single_issue', 'Grapa'), ('prestige', 'Prestige'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('ashcan', 'Ashcan'), ('digital', 'Digital'), ('magazine', 'Magazine')], default='single_issue', max_length=20),
        ),
    ]
