# Generated by Django 5.1.10 on 2026-01-04 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0076_alter_comic_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='number',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Debe ser un número entero o una fracción (ej: 3 o 1/2)', regex='^(\\d+|\\d+/\\d+)$')]),
        ),
    ]
