# Generated by Django 5.1.10 on 2026-02-12 05:28

import comics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0077_alter_comic_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1960), comics.models.Publishing.max_value_current_year], verbose_name='year'),
        ),
    ]
