# Generated by Django 5.1.10 on 2026-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0078_alter_publishing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
