# Generated by Django 5.1.10 on 2026-04-19 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0079_alter_dealer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='number',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Debe contener al menos un número', regex='\\d+')]),
        ),
    ]
