# Generated by Django 5.1.15 on 2026-09-25 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0080_alter_comic_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='printing',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th')], default='1st', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('comic', 'trade_date', 'amount', 'trade_type', 'participant'), name='unique_collection_comic_date_amount_type_participant'),
        ),
        migrations.AddConstraint(
            model_name='comic',
            constraint=models.UniqueConstraint(fields=('publishing', 'number', 'variant', 'printing'), name='unique_comic_publishing_number_variant_printing'),
        ),
        migrations.AddConstraint(
            model_name='publishing',
            constraint=models.UniqueConstraint(fields=('publishing_title', 'year', 'serie', 'language'), name='unique_publishing_title_year_serie_language'),
        ),
    ]
