# Generated by Django 5.1.15 on 2026-09-25 06:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0081_alter_comic_printing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connecting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rows', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('columns', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectingPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(default=1, help_text='1 = fila de arriba', validators=[django.core.validators.MinValueValidator(1)])),
                ('column', models.PositiveSmallIntegerField(help_text='1 = columna izquierda', validators=[django.core.validators.MinValueValidator(1)])),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connecting_pieces', to='comics.comic')),
                ('connecting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='comics.connecting')),
            ],
            options={
                'ordering': ['row', 'column'],
            },
        ),
        migrations.AddField(
            model_name='connecting',
            name='comics',
            field=models.ManyToManyField(related_name='connectings', through='comics.ConnectingPiece', to='comics.comic'),
        ),
        migrations.AddConstraint(
            model_name='connectingpiece',
            constraint=models.UniqueConstraint(fields=('connecting', 'row', 'column'), name='unique_connecting_position'),
        ),
        migrations.AddConstraint(
            model_name='connectingpiece',
            constraint=models.UniqueConstraint(fields=('connecting', 'comic'), name='unique_connecting_comic'),
        ),
    ]
