# Generated by Django 5.1.15 on 2026-09-26 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0082_connecting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('synopsis', models.TextField(blank=True)),
                ('creators', models.ManyToManyField(blank=True, related_name='issues', to='comics.artist')),
                ('publishing', models.ForeignKey(help_text='Serie original', on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='comics.publishing')),
            ],
            options={
                'ordering': ['publishing__publishing_title', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CollectedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_entries', to='comics.comic')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_entries', to='comics.issue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='comic',
            name='collected_issues',
            field=models.ManyToManyField(blank=True, related_name='collected_in', through='comics.CollectedIssue', to='comics.issue'),
        ),
        migrations.AddField(
            model_name='comic',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='comics.issue'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('publishing', 'number'), name='unique_issue_publishing_number'),
        ),
        migrations.AddConstraint(
            model_name='collectedissue',
            constraint=models.UniqueConstraint(fields=('edition', 'issue'), name='unique_collected_issue'),
        ),
        migrations.AddConstraint(
            model_name='collectedissue',
            constraint=models.UniqueConstraint(fields=('edition', 'order'), name='unique_collected_order'),
        ),
    ]
