# Generated by Django 5.1.15 on 2026-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0086_rename_comic_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='format',
            field=models.CharField(choices=[('single_issue', 'Single issue'), ('prestige', 'Prestige'), ('trade_paperback', 'TPB - Trade Paperback'), ('hardcover', 'HC - Hardcover'), ('ashcan', 'Ashcan'), ('digital', 'Digital'), ('magazine', 'Magazine')], default='single_issue', max_length=20),
        ),
    ]
