# Generated by Django 5.1.15 on 2026-09-26 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def ensure_story_arcs_empty(apps, schema_editor):
    """Safeguard: StoryArc is dropped, so it must be empty to avoid losing data."""
    StoryArc = apps.get_model("comics", "StoryArc")
    count = StoryArc.objects.count()
    if count:
        raise RuntimeError(f"There are {count} StoryArc rows. Move them to ReadingArc before dropping the model.")


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0087_format_choice_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingArcEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='comics.readingarc')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arc_entries', to='comics.issue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='readingarc',
            name='issues',
            field=models.ManyToManyField(related_name='reading_arcs', through='comics.ReadingArcEntry', to='comics.issue'),
        ),
        migrations.RunPython(ensure_story_arcs_empty, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='StoryArc',
        ),
        migrations.AddConstraint(
            model_name='readingarcentry',
            constraint=models.UniqueConstraint(fields=('arc', 'issue'), name='unique_reading_arc_issue'),
        ),
        migrations.AddConstraint(
            model_name='readingarcentry',
            constraint=models.UniqueConstraint(fields=('arc', 'order'), name='unique_reading_arc_order'),
        ),
    ]
