# Generated by Django 5.1.15 on 2026-09-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0088_reading_arcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='retailer_exclusive',
            field=models.CharField(blank=True, help_text='Store the cover is exclusive to (retailer exclusive). Empty for regular and incentive covers.', max_length=60),
        ),
    ]
