# Generated by Django 5.1.15 on 2026-09-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0089_edition_retailer_exclusive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='edition',
            name='unique_edition_publishing_number_variant_printing',
        ),
        migrations.AddField(
            model_name='edition',
            name='event_exclusive',
            field=models.CharField(blank=True, help_text='Event the cover is exclusive to (e.g. SDCC 2025). It can also have a store and a variant.', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(fields=('publishing', 'number', 'variant', 'printing', 'retailer_exclusive', 'event_exclusive'), name='unique_edition_publishing_number_variant_printing_exclusives'),
        ),
    ]
