# Generated by Django 5.1.15 on 2026-09-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0090_edition_event_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comics.edition'),
        ),
    ]
